#!/usr/bin/env perl

# Use perldoc or option --man to read documentation
our $version = '0.01';

########################################################################
# MODULES
########################################################################

# Include core modules.
use strict;
use warnings;
use File::Basename;
use Carp;

# Include CPAN modules.
use Getopt::Euclid qw{ :vars<opt_> };
use List::Util;
use File::Temp;
use Readonly;

# Include private modules.
use App::Pai::AlsaState;

########################################################################
# GENERAL GLOBAL VARIABLES
########################################################################

# Basic program information.
Readonly my $prog_incantation  => $0;
Readonly my $prog_dir          => dirname($0);
Readonly my $prog_name         => basename($0);

# Command-line option hash.
my %opt = %ARGV;

# Global program exitcode.
my $exitcode = 0;

########################################################################
# PROGRAM SPECIFIC GLOBALS
########################################################################

########################################################################
# MAIN FUNCTION
########################################################################

# main() - main program execution 
sub main{

    # Read the current alsa state.
    my $current_alsa_state = App::Pai::AlsaState->get(
        file => $opt{'--state-file'},
        card => $opt{'--card'},
    );

    my $headphone_volume_control 
        = App::Pai::AlsaState->find_control_named(
            'Headphone Playback Volume',
            $current_alsa_state);

    # Toggle any switches.
    my @to_toggle = @{$opt{'--toggle'} || []};
    for my $connection (@to_toggle) {
        #toggle($connection || 'master');
    }
    # Set volumes.
    my @volumes = @{$opt{'--set-volume'} || []};
    for my $conn_vol (@volumes) {
        #set_volume(
        #   $conn_vol->{'connection'} || 'master', 
        #   $conn_vol->{volume})
    }
    # Mute connections.
    my @to_mute = $opt{'--mute'};
    for my $connection (@to_mute) {
        #mute($connection || 'master');
    }
    # Set mic boost.
    my $mic_boost = $opt{'--set-mic-boost'};
    # do something here.

    App::Pai::AlsaState->control_level($headphone_volume_control, 0.5);

    my $state_string 
        = App::Pai::AlsaState->state_string($current_alsa_state);
    print $state_string;

    exit($exitcode);
}

########################################################################
# SUPPORTING SUBROUTINES
########################################################################


# Finally, kickstart the script
main();

__END__

=head1 NAME

pai - Perl based Alsa driver Interface

=head1 VERSION

Version 0.02
Originally created on 04/25/10 02:56:02

=head1 USAGE

pai [options]

=head1 REQUIRED ARGUMENTS

=over

=back

=head1 OPTIONS

=over

=item -c <target> | --card [=] <target>

Card #, ID, or device.

All devices are updated if not supplied.

=for Euclid:
    target.default: undef

=item -t [<connection>] | --toggle [=] [<connection>]

Toggle a connection from an inactive state to an active one, or vice 
versa, depending on its current state.

<connection> can be any of 'master', 'speaker', 'headphone', 'mic', 
or 'beep'.

'master' will be toggled if no connection is named.

=for Euclid:
	repeatable
	connection.type: /^(?:master|speaker|headphone|mic|beep)$/

=item -v [<connection>:]<volume> | --set-volume [=] [<connection>:]<volume>

Set the volume on a specified connection. 

<volume> is a percentage; a number in range [0,1].

'master' volume will be set if no connection is named.

You may specify multiple -v  options in one command. If you specify more
than one for the same connection the last one will take affect after the
program has completed.

=for Euclid:
	repeatable
	connection.type: /^(?:master|speaker|headphone|mic|beep|pcm)$/
	volume.type: number, 0 <= volume && volume <= 1

=item -m [<connection>] | --mute [=] [<connection>]

Mute a specified connection. 

'master' will be muted if no connection is specified.

This is identical to the option "--set-volume=<connection>:0",
but will take precidence over any other --set-volume option on the same
connection.

This option is repeatable.

=for Euclid:
	repeatable
	connection.type: /^(?:master|speaker|headphone|mic|beep|pcm)$/

=item -b <boost> | --set-mic-boost [=] <boost>

Specify the microphone boost value acceptable values of this may change 
depending on hardware.

=for Euclid:
	boost.type: 0+integer

=item -i [<control>] | --info [=] [<control>]

Print information a specific control (or all if none specified) in the 
current alsa state (or the alsa state provided via the -f option).
This information includes acceptable volume levels for the given 
control.

=for Euclid:
	repeatable
	control.type: +integer

=item -f <file> | --state-file [=] <file>

An alsa configuration state file to read in, instead of reading the 
current alsa state from alsactl.

=for Euclid:
	file.type: readable

=item --version

=item --usage

=item --help

=item --man

Print the usual program information

=back

=head1 DESCRIPTION

With this program, a user can update their audio settings via a single 
command, as opposed to gnome-volume-manager and alsamixer.

Some examples of tasks that should be doable via pai:

=over

=item Toggle master, headphone, speaker, mic, and beep switches.

It turns out to be a bad idea to toggle the anything except master and mic
(possibly beep?)

=item Adjust volume (master, speaker, headphone, mic, beep)

I can do this on a low level now.

=item Microphone boost

=item PCM (pulse-code-modulation) volume

=back

Some things that pai will probably never do:

=over

=item Modify control comments I don't want to mess around with 
acceptable decibal/volume/value ranges. These values will be parsed, 
but they will not be modifiable.

=back

=head1 BUGS

=over

=back

=head1 AUTHOR & COPYRIGHT 

©Bryan Matsuo (bryan.matsuo@gmail.com)

